# Generated by Django 4.2.4 on 2023-08-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_actualizado_campos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='ciudad',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
